In [158]:
# tips data
#  all 4 encoding 
#  standerization 
#  normalization 

#  titanic data remove outliers

In [159]:
import pandas as pd 
import numpy as np 
import seaborn as sns

In [160]:
df = sns.load_dataset("Tips")

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [162]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [163]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder

In [164]:
lb = LabelEncoder()

In [165]:
df_LE = df.copy()

In [166]:
df_cat = df.select_dtypes(include='object').columns

In [167]:
for x in df_cat:
    df_LE[x] = lb.fit_transform(df_LE[x])

In [168]:
df_LE

     total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    2     0     2
1         10.34  1.66    1       0    2     0     3
2         21.01  3.50    1       0    2     0     3
3         23.68  3.31    1       0    2     0     2
4         24.59  3.61    0       0    2     0     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    1     0     3
240       27.18  2.00    0       1    1     0     2
241       22.67  2.00    1       1    1     0     2
242       17.82  1.75    1       0    1     0     2
243       18.78  3.00    0       0    3     0     2

[244 rows x 7 columns]

In [169]:
# ordinal encoder :-

In [170]:
df_oe = df.copy()

In [171]:
df_oe

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [172]:
df['day'].unique()

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [173]:
df['time'].unique()

array(['Dinner', 'Lunch'], dtype=object)

In [174]:
oe = OrdinalEncoder(categories = [['Female', 'Male' ],
                                ['No','Yes'],
                                ['Sun', 'Sat', 'Thur', 'Fri'],
                                ['Dinner', 'Lunch']])

In [175]:
df_oe_cat = df_oe.select_dtypes(include='object')

In [176]:
df_oe = oe.fit_transform(df_oe_cat)

In [178]:
df_oe = pd.DataFrame(df_oe_cat , columns = df_oe_cat.columns)

In [ ]:
df_oe

     sex  smoker  day  time
0    0.0     0.0  0.0   0.0
1    1.0     0.0  0.0   0.0
2    1.0     0.0  0.0   0.0
3    1.0     0.0  0.0   0.0
4    0.0     0.0  0.0   0.0
..   ...     ...  ...   ...
239  1.0     0.0  1.0   0.0
240  0.0     1.0  1.0   0.0
241  1.0     1.0  1.0   0.0
242  1.0     0.0  1.0   0.0
243  0.0     0.0  2.0   0.0

[244 rows x 4 columns]

In [179]:
#  one hot encoder :-

In [180]:
df_ohe = df.copy()

In [181]:
ohe = OneHotEncoder(drop = 'first' , sparse_output = False , dtype = np.int32)

In [182]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [183]:
df_ohe = ohe.fit_transform(df[['sex', 'smoker', 'day', 'time']])

In [184]:
df_ohe

array([[0, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 0],
       ...,
       [1, 1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0]], shape=(244, 6), dtype=int32)

In [185]:
# standerizing :-

In [186]:
from sklearn.preprocessing import StandardScaler

In [187]:
sc = StandardScaler()

In [193]:
# df_LE

In [188]:
df_LE_sc = sc.fit_transform(df_LE)

In [197]:
df_LE_sc = pd.DataFrame(df_LE_sc , columns = df_LE.columns)  # converting it into df

In [198]:
np.round(df_LE_sc.describe() , 2)        # now the mean and std daviation is same for all columns

       total_bill     tip     sex  smoker     day    time    size
count      244.00  244.00  244.00  244.00  244.00  244.00  244.00
mean        -0.00    0.00   -0.00    0.00   -0.00    0.00   -0.00
std          1.00    1.00    1.00    1.00    1.00    1.00    1.00
min         -1.88   -1.45   -1.34   -0.78   -1.88   -0.62   -1.65
25%         -0.72   -0.72   -1.34   -0.78   -0.80   -0.62   -0.60
50%         -0.22   -0.07    0.74   -0.78    0.28   -0.62   -0.60
75%          0.49    0.41    0.74    1.27    1.36    1.61    0.45
max          3.49    5.07    0.74    1.27    1.36    1.61    3.61

In [199]:
# normalizing using min max :-

In [200]:
from sklearn.preprocessing import MinMaxScaler

In [201]:
mn = MinMaxScaler()

In [202]:
df_LE_mx = mn.fit_transform(df_LE)

In [203]:
df_Le_mx = pd. DataFrame(df_LE_mx, columns = df_LE. columns)

In [204]:
np.round(df_LE_sc.describe() , 2)

       total_bill     tip     sex  smoker     day    time    size
count      244.00  244.00  244.00  244.00  244.00  244.00  244.00
mean        -0.00    0.00   -0.00    0.00   -0.00    0.00   -0.00
std          1.00    1.00    1.00    1.00    1.00    1.00    1.00
min         -1.88   -1.45   -1.34   -0.78   -1.88   -0.62   -1.65
25%         -0.72   -0.72   -1.34   -0.78   -0.80   -0.62   -0.60
50%         -0.22   -0.07    0.74   -0.78    0.28   -0.62   -0.60
75%          0.49    0.41    0.74    1.27    1.36    1.61    0.45
max          3.49    5.07    0.74    1.27    1.36    1.61    3.61

In [205]:
# pipeline and column transformer for encoding and standerization :-

In [207]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [208]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [209]:
transformer = ColumnTransformer(transformers=[
('tnf',OneHotEncoder(sparse_output=False, drop='first' ), ['sex' , 'smoker' , 'day' , 'time'])
],remainder='passthrough')

In [213]:
categorical_transformer = Pipeline(steps=[
('ct', transformer),
('stnd', StandardScaler())
])

In [214]:
categorical_transformer

Pipeline(steps=[('ct',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('tnf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['sex', 'smoker', 'day',
                                                   'time'])])),
                ('stnd', StandardScaler())])