In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\codings\datasets\covid_toy - covid_toy.csv")

In [3]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [4]:
df.isna().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
df = df.dropna()

In [6]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
lb = LabelEncoder()

In [9]:
df_cat = df.select_dtypes(include='object').columns

In [10]:
for x in df_cat:
    df[x] = lb.fit_transform(df[x])

In [11]:
df.head()

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0
4   65       0  101.0      0     3          0

In [12]:
X = df.drop(columns=['has_covid'])

In [13]:
y = df['has_covid']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
random_state=42)

In [15]:
base_learners = []
num_base_learners = 10

In [17]:
for i in range(num_base_learners):
    bootstrap_indices = np.random.choice(len(X_train), size=len(X_train),
    replace=True)
    X_bootstrap = X_train.iloc[bootstrap_indices]
    y_bootstrap = y_train.iloc[bootstrap_indices]

    base_learner = RandomForestClassifier(n_estimators=10, random_state=42)
    base_learner.fit(X_bootstrap, y_bootstrap)

    base_learners.append(base_learner)

In [18]:
base_predictions = []
for base_learner in base_learners:
    y_pred = base_learner.predict(X_test)
    base_predictions.append(y_pred)

In [ ]:
ensemble_predictions = np.round(np.mean(base_predictions, axis=0))

accuracy = accuracy_score(y_test, ensemble_predictions)
print("Ensemble Accuracy:", accuracy)

Ensemble Accuracy: 0.3888888888888889